version: "3.8"

services:
  userapi:
    build: ./UserAPI
    container_name: userapi
    ports:
      - "8000:8000"
    env_file:
      - .env # Load environment variables from .env file
    depends_on:
      - dynamodb
    networks:
      - app_network

  scoreapi:
    build: ./ScoreAPI
    container_name: scoreapi
    ports:
      - "8001:8000"
    env_file:
      - .env # Load environment variables from .env file
    depends_on:
      - userapi
      - metadataapi
    networks:
      - app_network

  metadataapi:
    build: ./MetadataAPI
    container_name: metadataapi
    ports:
      - "8002:8000"
    env_file:
      - .env # Load environment variables from .env file
    depends_on:
      - userapi
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
