services:
  userapi:
    build: ./UserAPI
    container_name: userapi
    ports:
      - "8000:8000"
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - app_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/"]
      interval: 30s
      timeout: 10s
      retries: 3

  metadataapi:
    build: ./MetadataAPI
    container_name: metadataapi
    ports:
      - "8002:8000"
    env_file:
      - .env
    restart: unless-stopped
    depends_on:
      userapi:
        condition: service_healthy
    networks:
      - app_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/"]
      interval: 30s
      timeout: 10s
      retries: 3

  scoreapi:
    build: ./ScoreAPI
    container_name: scoreapi
    ports:
      - "8001:8000"
    env_file:
      - .env
    restart: unless-stopped
    depends_on:
      userapi:
        condition: service_healthy
      metadataapi:
        condition: service_healthy
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
